In [1]:
import pandas as pd
import numpy as np

In [2]:
af = pd.read_csv('airfoil_self_noise.dat', sep='\t', header=None)

In [3]:
af.head(10)

0    1       2     3         4        5
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461
5  2500  0.0  0.3048  71.3  0.002663  125.571
6  3150  0.0  0.3048  71.3  0.002663  125.201
7  4000  0.0  0.3048  71.3  0.002663  123.061
8  5000  0.0  0.3048  71.3  0.002663  121.301
9  6300  0.0  0.3048  71.3  0.002663  119.541

In [4]:
af.columns = ['Frequency', 'Angle_of_attack', 'Chord_length', 'velocity', 'thickness', 'Noise']
af.head()

Frequency  Angle_of_attack  Chord_length  velocity  thickness    Noise
0        800              0.0        0.3048      71.3   0.002663  126.201
1       1000              0.0        0.3048      71.3   0.002663  125.201
2       1250              0.0        0.3048      71.3   0.002663  125.951
3       1600              0.0        0.3048      71.3   0.002663  127.591
4       2000              0.0        0.3048      71.3   0.002663  127.461

In [5]:
af.shape

(1503, 6)

In [6]:
X = af.drop('Noise', axis = 1)
y = af['Noise']

In [7]:
X.shape, y.shape

((1503, 5), (1503,))

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

#### Using Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression
lc = LinearRegression()

In [11]:
lc.fit(X_train, y_train)

LinearRegression()

In [12]:
lc.score(X_train, y_train)

0.5273913183155836

In [13]:
y_preds = lc.predict(X_test)

In [14]:
y_preds

array([119.37418837, 118.72298437, 125.39507796, 117.2038744 ,
       122.47401457, 115.41026959, 117.29251681, 122.47309805,
       126.78840517, 124.11601016, 131.32283233, 122.94906998,
       125.18956478, 118.92207845, 121.39766041, 121.15001909,
       134.13171361, 133.34682042, 127.51177996, 120.0672397 ,
       127.75223353, 125.29473087, 134.13604936, 124.76337459,
       119.23729479, 123.30255896, 127.1194658 , 122.69859957,
       127.26780321, 125.68589644, 121.96735185, 110.77238534,
       126.58739199, 128.60627897, 117.16573725, 135.11485128,
       122.82234986, 121.69449005, 120.89515079, 123.80841414,
       126.35219742, 117.26196628, 125.43834469, 125.13153499,
       118.24850245, 128.0318741 , 129.03653203, 120.33907606,
       124.82336126, 121.94745604, 116.69160236, 129.76984633,
       119.19459972, 127.04137022, 111.50758799, 122.40779262,
       123.93560615, 125.5741976 , 121.30143359, 127.5756434 ,
       122.8740631 , 131.60143658, 120.83885153, 128.06

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [16]:
y_preds = lc.predict(X_test)
mae = mean_absolute_error(y_test, y_preds)
mae

3.6865682959121115

In [17]:
y_preds = lc.predict(X_test)
mse = print(mean_squared_error(y_test, y_preds))
mse

22.79755316822762


#### Using Logistic Regression

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
rfr = RandomForestRegressor()

In [21]:
rfr.fit(X_train, y_train)

RandomForestRegressor()

In [22]:
rfr.score(X_train,y_train)

0.991031145727694

In [23]:
y_preds = rfr.predict(X_test)

In [24]:
y_preds

array([122.13042, 127.67597, 126.89883, 129.81878, 118.49748, 125.78469,
       120.05861, 124.72174, 121.69169, 122.11039, 129.20767, 131.71786,
       127.77216, 130.82497, 116.02813, 133.24392, 124.85038, 128.66189,
       134.21381, 121.53496, 127.33878, 130.15231, 121.77967, 119.79338,
       124.90021, 135.28002, 114.19063, 116.85953, 113.90493, 120.24304,
       121.123  , 125.75891, 124.58259, 129.461  , 129.00061, 121.70062,
       113.87089, 127.50457, 118.21131, 134.53058, 118.37409, 122.87753,
       125.55474, 125.16334, 118.83698, 129.21845, 123.78958, 130.24137,
       128.6254 , 127.84669, 118.25551, 122.99211, 130.11914, 133.33225,
       120.85169, 121.92186, 114.82218, 132.80285, 131.4651 , 126.12425,
       127.54707, 127.11315, 129.1198 , 132.82254, 130.41939, 123.29056,
       128.91165, 133.93551, 117.57963, 128.1646 , 120.77946, 117.71569,
       131.66418, 125.55221, 123.68521, 116.45096, 126.4672 , 126.99467,
       127.07924, 115.34717, 126.70484, 113.92754, 

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [26]:
mae = mean_absolute_error(y_test, y_preds)
mae

1.310666179401995

In [27]:
mse = mean_squared_error(y_test, y_preds)
mse

3.3153987378804346

### Using MLP Regressor

In [28]:
from sklearn.neural_network import MLPRegressor

In [29]:
mlpr = MLPRegressor()

In [30]:
mlpr.fit(X_train, y_train)

MLPRegressor()

In [31]:
mlpr.score(X_train, y_train)

-24.5205703155661

In [32]:
y_preds = mlpr.predict(X_test)

In [33]:
y_preds

array([ 90.0322498 ,  98.64655715,  75.62374838, 126.34484809,
       171.59739856,  82.86653168, 105.73123503, 115.45958059,
        81.41348468, 118.76470167,  67.76521905, 151.43597613,
       185.04874471,  95.38036571, 132.39107454, 162.60057958,
       168.86482283, 158.37673039, 125.12239976,  85.10889175,
       127.5260546 , 102.52109476, 180.15871949,  87.93685258,
        87.490947  , 160.96426627, 110.1148313 ,  89.69958382,
       102.38976021,  73.45695839,  95.50684834,  84.11735543,
       155.02916991, 147.24948943,  83.55260043, 169.12948045,
        90.86096372,  90.61435163, 129.54188477,  74.68740646,
       127.57223653, 123.71147849, 129.59337337,  73.12180229,
        96.16475197,  92.8596309 , 132.278245  , 140.45625648,
       103.95331389, 115.01291062,  95.8980209 , 172.81836843,
        90.4838698 , 127.77706722, 155.34787816,  82.67729456,
       107.25039303,  74.15581331, 160.02699325, 118.37815116,
       158.96791072,  98.27407863, 159.99738316, 149.87

In [34]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [35]:
mae = mean_absolute_error(y_test, y_preds)
mae

29.508361561330393

In [36]:
mse = mean_squared_error(y_test, y_preds)
mse

1153.3199615157491

Thus, it is clear that on using different algorithms on the problem, I can conclude that Logistic regrssion model provide us most accurate result.