In [1]:
import pandas as pd
import numpy as np

In [2]:
af = pd.read_csv('airfoil_self_noise.dat', sep='\t', header=None)

In [3]:
af.head(10)

0    1       2     3         4        5
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461
5  2500  0.0  0.3048  71.3  0.002663  125.571
6  3150  0.0  0.3048  71.3  0.002663  125.201
7  4000  0.0  0.3048  71.3  0.002663  123.061
8  5000  0.0  0.3048  71.3  0.002663  121.301
9  6300  0.0  0.3048  71.3  0.002663  119.541

In [4]:
af.columns = ['Frequency', 'Angle_of_attack', 'Chord_length', 'velocity', 'thickness', 'Noise']
af.head()

Frequency  Angle_of_attack  Chord_length  velocity  thickness    Noise
0        800              0.0        0.3048      71.3   0.002663  126.201
1       1000              0.0        0.3048      71.3   0.002663  125.201
2       1250              0.0        0.3048      71.3   0.002663  125.951
3       1600              0.0        0.3048      71.3   0.002663  127.591
4       2000              0.0        0.3048      71.3   0.002663  127.461

In [5]:
af.shape

(1503, 6)

In [6]:
X = af.drop('Noise', axis = 1)
y = af['Noise']

In [7]:
X.shape, y.shape

((1503, 5), (1503,))

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

#### Using Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression
lc = LinearRegression()

In [11]:
lc.fit(X_train, y_train)

LinearRegression()

In [12]:
lc.score(X_train, y_train)

0.5192530801316875

In [13]:
y_preds = lc.predict(X_test)

In [14]:
y_preds

array([115.87482614, 131.83715637, 126.61025948, 116.69545382,
       129.80861404, 121.15384115, 130.03579595, 124.93848195,
       128.11288814, 128.75884832, 119.26171282, 126.15310975,
       122.0144377 , 125.57993432, 120.72900856, 122.2951366 ,
       131.61118861, 127.97972375, 125.73209085, 121.46919587,
       121.82104446, 122.33297892, 123.6440517 , 130.89713094,
       121.29403657, 124.02646598, 122.43648723, 122.87659367,
       130.75206777, 116.19088627, 125.84879799, 124.78789707,
       121.50362822, 120.63006342, 128.52209329, 129.45666003,
       119.26490755, 123.36972753, 125.66485835, 129.5807251 ,
       121.4467992 , 130.11513524, 125.64441871, 133.70224416,
       123.33032765, 127.41191816, 123.98476362, 130.67513786,
       129.75719607, 122.77128903, 123.5640746 , 126.15169973,
       129.13727398, 126.9674951 , 122.76261903, 125.97537778,
       122.62622586, 129.91798751, 122.29752147, 129.77693002,
       130.73880717, 127.29155976, 124.44944308, 129.34

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [16]:
y_preds = lc.predict(X_test)
mae = mean_absolute_error(y_test, y_preds)
mae

3.73845647377362

In [17]:
y_preds = lc.predict(X_test)
mse = print(mean_squared_error(y_test, y_preds))
mse

23.632366905008478


#### Using Logistic Regression

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
rfr = RandomForestRegressor()

In [21]:
rfr.fit(X_train, y_train)

RandomForestRegressor()

In [22]:
rfr.score(X_train,y_train)

0.9908422205626796

In [23]:
y_preds = rfr.predict(X_test)

In [24]:
y_preds

array([112.2306 , 128.85545, 117.78177, 132.36008, 119.26712, 130.06412,
       123.67633, 131.20023, 113.13036, 130.25341, 130.58759, 127.80203,
       121.08752, 125.42947, 123.96376, 124.50589, 125.07395, 127.90814,
       128.2371 , 126.637  , 132.5715 , 120.59583, 122.82254, 132.57071,
       123.94307, 118.87211, 128.83957, 124.13464, 130.08215, 114.27523,
       119.35202, 117.98216, 122.44711, 120.36285, 127.22827, 117.19609,
       125.2919 , 117.35664, 125.78705, 124.50374, 119.77964, 125.73803,
       132.54495, 117.78878, 129.56209, 128.64241, 126.58582, 124.40981,
       129.36013, 136.60495, 116.29926, 126.62304, 121.87052, 128.94471,
       129.3301 , 118.99183, 127.08775, 124.05903, 126.30937, 132.93013,
       125.34272, 128.31423, 116.81599, 134.11966, 126.17071, 126.63098,
       127.81894, 121.05087, 111.38418, 116.73487, 133.03027, 133.72265,
       123.09434, 124.84615, 133.85855, 131.87118, 121.62245, 130.72347,
       114.28103, 121.25021, 130.29735, 121.82095, 

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [26]:
mae = mean_absolute_error(y_test, y_preds)
mae

1.2346559468438592

In [27]:
mse = mean_squared_error(y_test, y_preds)
mse

3.277710658007983

In [28]:
np.sqrt(mse)

1.8104448784782108

### Using MLP Regressor

In [29]:
from sklearn.neural_network import MLPRegressor

In [30]:
mlpr = MLPRegressor()

In [31]:
mlpr.fit(X_train, y_train)

MLPRegressor()

In [32]:
mlpr.score(X_train, y_train)

-23.413440693890934

In [33]:
y_preds = mlpr.predict(X_test)

In [34]:
y_preds

array([ 91.15001152,  67.14064329, 157.73146967,  67.45780753,
        90.17114687,  98.21040388, 167.8393677 , 166.66320033,
       101.92230687, 114.42297587, 162.61538695, 161.39563354,
        90.55008172, 148.15667963, 177.53767662, 101.12909172,
       189.07761338, 146.67015892,  82.51490266, 145.25763982,
       119.96645253, 189.55319439, 108.07689856, 123.45921618,
       120.31842397,  95.38253082, 113.74985668, 101.72820845,
        89.37586202, 118.34589032, 154.9676694 ,  93.39085901,
        90.69892576, 107.70412352, 107.51521984,  80.45837007,
       115.87731377, 166.76090193,  80.80178453,  81.24677291,
        63.81635317, 151.14109378, 162.0071268 ,  97.6895248 ,
       158.5097756 , 119.48210501, 148.02142625,  91.63400214,
        71.00494914, 118.96900755,  92.26189502, 101.95954843,
       166.58824217, 126.98506357, 142.15402992,  99.37872122,
        76.0932061 ,  95.24670369,  66.40269741,  89.62187134,
       180.22904764, 156.07770156, 158.23572925,  93.67

In [35]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [36]:
mae = mean_absolute_error(y_test, y_preds)
mae

30.875667340314493

In [37]:
mse = mean_squared_error(y_test, y_preds)
mse

1245.4250544324202

Thus, it is clear that on using different algorithms on the problem, I can conclude that Logistic regrssion model provide us most accurate result.

In [38]:
np.sqrt(mse)

35.29058025071875